Repository open-sdg/open-sdg, pull requests merged in 2020-03, with the labels that each got.

#523 Accessibility tests for mobile and high-contrast
  Makefile
  _sass/components/_download_buttons.scss
  _sass/layouts/_indicator.scss
  tests/accessibility/README.md
  tests/accessibility/pa11yci-contrast.json
  tests/accessibility/pa11yci-desktop.json
  tests/accessibility/pa11yci-mobile.json
Labels: 1.0.0

#530 Documentation of reserved metadata fields
  docs/metadata-format.md
  tests/data/_prose.yml
  tests/data/meta/1-1-1.md
  tests/data/meta/1-2-1.md
  tests/data/meta/1-3-1.md
  tests/data/meta/1-4-1.md
  tests/data/meta/1-4-2.md
  tests/data/meta/1-5-1.md
  tests/data/meta/1-5-2.md
  tests/data/meta/1-5-3.md
  tests/data/meta/1-5-4.md
  tests/data/meta/2-2-2.md
  tests/data/meta/2-3-2.md
  tests/data/meta/3-1-1.md
Labels: 1.0.0

#475 GeoJSON revamp: data in repo
  Makefile
  _includes/assets/js/indicatorModel.js
  _includes/assets/js/indicatorView.js
  _includes/assets/js/mapView.js
  _includes/assets/js/plugins/jquery.sdgMap.js
  _includes/assets/js/plugins/leaflet.downloadGeoJson.js
  _includes/assets/js/plugins/leaflet.selectionLegend.js
  _includes/assets/js/plugins/leaflet.yearSlider.js
  _includes/scripts.html
  _layouts/indicator.html
  _sass/components/_maps.scss
  assets/js/sdg.js
  docs/maps.md
  docs/requirements.md
  tests/data/config_data.yml
  tests/data/data/indicator_1-3-1.csv
  tests/data/translations/en/data.yml
  tests/data/translations/en/indicator.yml
  tests/data/translations/es/data.yml
  tests/data/translations/es/indicator.yml
  tests/data/translations/fr/data.yml
  tests/data/translations/fr/indicator.yml
  tests/features/Disaggregation.feature
  tests/features/Map.feature
  tests/site/_config.yml
Labels: 1.0.0, maps

#545 Change frontpage introduction banner config
  _layouts/frontpage.html
Labels: 1.0.0

#549 Documentation link fixes and testing
  .gitignore
  Makefile
  docs/about.md
  docs/configuration.md
  docs/customisation.md
  docs/data-sources.md
  docs/development.md
  docs/faq.md
  docs/making-updates.md
  docs/metadata-format.md
  docs/open-sdg-features.md
  docs/quick-start.md
  docs/reporting-status.md
  docs/translation.md
  docs/upgrading.md
Labels: 1.0.0

#533 Update styling of progress bars
  _sass/base/_mixins.scss
  _sass/layouts/_goal.scss
  _sass/layouts/_reporting_status.scss
  tests/data/meta/1-2-2.md
  tests/data/meta/4-1-1.md
Labels: 1.0.0

#526 More detailed documentation on 'reporting_status_extra_fields'
  docs/reporting-status.md
Labels: 1.0.0, docs

#524 Documentation and tests for the 'tags' metadata field
  docs/metadata-format.md
  tests/data/meta/1-1-1.md
  tests/data/translations/en/tags.yml
  tests/data/translations/es/tags.yml
  tests/data/translations/fr/tags.yml
  tests/features/Tags.feature
Labels: 1.0.0, docs

#565 Make the introduction banner work in high contrast
  _sass/components/_high_contrast.scss
  tests/features/Homepage.feature
  tests/site/_config.yml
Labels: 1.0.0

#572 Increase the font size of the header navigation menu
  _sass/layouts/_header.scss
Labels: 1.0.0, Expert review

#525 Documentation of the chart types
  _includes/assets/js/indicatorModel.js
  _includes/components/charts/bar.html
  _includes/components/charts/hide_headline.html
  _includes/components/charts/line.html
  _includes/components/charts/stacked_bar.html
  _includes/scripts.html
  _layouts/indicator.html
  docs/charts.md
  docs/metadata-format.md
  docs/open-sdg-features.md
  mkdocs.yml
  tests/data/data/indicator_2-3-1.csv
  tests/data/meta/2-3-1.md
Labels: 1.0.0, docs

#587 Remove table-hover class and styling
  _includes/components/metadata.html
Labels: 1.0.0, Expert review
