Repository open-sdg/open-sdg, pull requests merged in 2020-04, with the labels that each got.

#594 Indicator cards styling updates
  _sass/base/_mixins.scss
  _sass/layouts/_indicator.scss
Labels: 1.0.0, Expert review

#588 Various fixes to make more elements flush to the left
  _sass/components/_disclaimer.scss
  _sass/components/_download_buttons.scss
  _sass/layouts/_footer.scss
  _sass/layouts/_header.scss
  _sass/layouts/_indicator.scss
Labels: 1.0.0, Expert review

#573 Make indicator links in goal page appear clickable
  _sass/base/_mixins.scss
  _sass/layouts/_goal.scss
  _sass/layouts/_indicator.scss
  tests/accessibility/pa11yci-contrast.json
  tests/accessibility/pa11yci-desktop.json
  tests/accessibility/pa11yci-mobile.json
Labels: 1.0.0, Expert review

#611 Documentation link audit and translation docs
  Makefile
  docs/about.md
  docs/architecture.md
  docs/automation/travis-ci.md
  docs/configuration.md
  docs/customisation.md
  docs/data-sources.md
  docs/development.md
  docs/faq.md
  docs/glossary.md
  docs/hosting/aws-s3.md
  docs/hosting/github-pages.md
  docs/hosting/linux-server.md
  docs/index.md
  docs/making-updates.md
  docs/metadata-file-formats.md
  docs/metadata-format.md
  docs/open-sdg-features.md
  docs/quick-start.md
  docs/reporting-status.md
  docs/social-media-sharing.md
  docs/translation.md
  docs/upgrading.md
  mkdocs.yml
Labels: 1.0.0

#615 Convert to high-contrast images as page loads
  _includes/assets/js/accessibility.js
Labels: 1.0.0

#403 Changelog entry for 1.0.0 with upgrade instructions and non-technical updates
  Makefile
  docs/changelog.md
  docs/updates.md
  docs/upgrading-1-0-0.md
  mkdocs.yml
Labels: 1.0.0

#548 Production environment docs
  docs/changelog.md
  docs/deployment.md
  docs/hosting/github-pages-production.md
  docs/hosting/github-pages.md
  docs/hosting/production.md
  docs/upgrades/upgrade-process.md
  docs/upgrades/upgrading-1-0-0.md
  mkdocs.yml
Labels: 1.0.0

#617 Highlight the high-contrast goal icons on hover
  _sass/components/_high_contrast.scss
Labels: 1.0.0

#622 [Expert review] Goal page styling updates
  _sass/base/_mixins.scss
  _sass/layouts/_indicator.scss
Labels: 1.0.0

#618 Font size 14px for long contrast switcher
  _sass/components/_high_contrast.scss
Labels: 1.0.0

#619 Make high-contrast footer white by default, yellow on hover
  _sass/components/_high_contrast.scss
Labels: 1.0.0

#621 High-contrast support for y-axis scale label
  _includes/assets/js/indicatorView.js
Labels: 1.0.0

#620 Disclaimer redesign
  _includes/components/dev-disclaimer.html
  _sass/components/_disclaimer.scss
  _sass/components/_high_contrast.scss
  docs/changelog.md
  docs/configuration.md
  docs/updates.md
  tests/data/translations/en/custom.yml
  tests/data/translations/es/custom.yml
  tests/data/translations/fr/custom.yml
  tests/features/Disclaimer.feature
  tests/features/Search.feature
  tests/site/_config.yml
Labels: 1.0.0

#625 Update some Github code line links
  docs/changelog.md
  docs/reporting-status.md
  docs/upgrades/upgrading-1-0-0.md
Labels: 1.0.0, docs

#639 Make the configuration documentation alphabetical
  docs/configuration.md
Labels: 1.0.0

#648 Fix changelog format and clarify moved includes
  docs/changelog.md
Labels: 1.0.0
